name: Blessings
main: me.Nekoyoubi.Blessings.Blessings
version: 0.2
commands:
    blessings:
        description: Displays help text for Blessings.
        usage: /<command>
        aliases: b
    faith:
        description: Displays the user's current level.
        usage: /<command>
        aliases: xp